with open('src/pages/ManufacturerDashboard.jsx', 'w', encoding='utf-8') as f:
    f.write("""import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { useAuth } from "../context/AuthContext";
import { useNavigate } from "react-router-dom";
import API from "../utils/api";
const Sidebar = ({ active, setActive, logout, user }) => {
  const items = [{id:"dashboard",label:"Dashboard"},{id:"drugs",label:"My Drugs"},{id:"batches",label:"Batches"},{id:"qrcodes",label:"QR Codes"},{id:"supplychain",label:"Supply Chain"}];
  return (<div className="w-64 bg-primary-900 min-h-screen flex flex-col"><div className="p-6 border-b border-primary-700"><span className="text-white text-xl font-bold">DrugVerify</span><p className="text-blue-300 text-xs mt-1">Manufacturer Portal</p></div><div className="p-4 border-b border-primary-700"><p className="text-white text-sm truncate">{user?.company_name||user?.email}</p></div><nav className="flex-1 p-4 space-y-1">{items.map(i=>(<button key={i.id} onClick={()=>setActive(i.id)} className={"w-full text-left px-4 py-3 rounded-xl transition "+(active===i.id?"bg-primary-600 text-white":"text-blue-200 hover:bg-primary-800")}>{i.label}</button>))}</nav><div className="p-4 border-t border-primary-700"><button onClick={logout} className="w-full text-left px-4 py-3 rounded-xl text-blue-200 hover:bg-primary-800">Logout</button></div></div>);
};
const StatCard = ({title,value,icon,color}) => (<motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className={"rounded-2xl p-6 flex items-center gap-4 "+color}><div className="text-4xl">{icon}</div><div><p className="text-sm opacity-70">{title}</p><p className="text-3xl font-bold">{value??0}</p></div></motion.div>);
export default function ManufacturerDashboard() {
  const {user,logout} = useAuth(); const navigate = useNavigate();
  const [active,setActive] = useState("dashboard");
  const [drugs,setDrugs] = useState([]); const [stats,setStats] = useState(null);
  const [showAddDrug,setShowAddDrug] = useState(false);
  const [selectedDrug,setSelectedDrug] = useState(null);
  const [batches,setBatches] = useState([]);
  const [showAddBatch,setShowAddBatch] = useState(false);
  const [qrImage,setQrImage] = useState(null); const [qrBatch,setQrBatch] = useState("");
  const [drugForm,setDrugForm] = useState({name:"",generic_name:"",nafdac_number:"",description:"",dosage_form:"",strength:""});
  const [batchForm,setBatchForm] = useState({batch_number:"",manufacture_date:"",expiry_date:"",quantity:""});
  const [loading,setLoading] = useState(false);
  const [msg,setMsg] = useState(""); const [msgType,setMsgType] = useState("ok");
  useEffect(()=>{fetchDrugs();fetchStats();},[]);
  const showMsg=(t,tp="ok")=>{setMsg(t);setMsgType(tp);setTimeout(()=>setMsg(""),4000);};
  const fetchDrugs=async()=>{try{const r=await API.get("/drugs/");setDrugs(r.data.results||r.data);}catch(e){}};
  const fetchStats=async()=>{try{const r=await API.get("/analytics/dashboard/");setStats(r.data);}catch(e){}};
  const fetchBatches=async(id)=>{try{const r=await API.get("/drugs/"+id+"/batches/");setBatches(r.data.results||r.data);}catch(e){}};
  const handleAddDrug=async(e)=>{e.preventDefault();setLoading(true);try{await API.post("/drugs/",drugForm);showMsg("Drug added!");setShowAddDrug(false);setDrugForm({name:"",generic_name:"",nafdac_number:"",description:"",dosage_form:"",strength:""});fetchDrugs();fetchStats();}catch(err){showMsg(err.response?.data?.nafdac_number?.[0]||"Error","err");}setLoading(false);};
  const handleAddBatch=async(e)=>{e.preventDefault();setLoading(true);try{await API.post("/drugs/"+selectedDrug.id+"/batches/",batchForm);showMsg("Batch added!");setShowAddBatch(false);setBatchForm({batch_number:"",manufacture_date:"",expiry_date:"",quantity:""});fetchBatches(selectedDrug.id);fetchStats();}catch(err){showMsg("Error adding batch","err");}setLoading(false);};
  const handleGetQR=async(batch)=>{try{const r=await API.get("/drugs/batches/"+batch.id+"/qr/");setQrImage(r.data.qr_image_base64);setQrBatch(batch.batch_number);setActive("qrcodes");}catch(e){showMsg("QR error","err");}};
  const navTo=(id)=>{setActive(id);if(id==="drugs")fetchDrugs();};
  return (
    <div className="flex min-h-screen bg-gray-50">
      <Sidebar active={active} setActive={navTo} logout={()=>{logout();navigate("/");}} user={user} />
      <div className="flex-1 p-8 overflow-y-auto">
        <div className="flex justify-between items-center mb-8">
          <div><h1 className="text-2xl font-bold text-gray-900">{active==="dashboard"?"Dashboard":active==="drugs"?"My Drugs":active==="batches"?"Batches":active==="qrcodes"?"QR Codes":"Supply Chain"}</h1><p className="text-gray-500 mt-1">Welcome, {user?.company_name||user?.email}</p></div>
          <span className={"px-3 py-1 rounded-full text-sm font-medium "+(user?.is_verified?"bg-green-100 text-green-700":"bg-yellow-100 text-yellow-700")}>{user?.is_verified?"Verified":"Pending"}</span>
        </div>
        {msg&&<motion.div initial={{opacity:0}} animate={{opacity:1}} className={"px-4 py-3 rounded-lg mb-4 text-sm "+(msgType==="err"?"bg-red-50 text-red-600":"bg-green-50 text-green-700")}>{msg}</motion.div>}
        {active==="dashboard"&&(<div className="space-y-6"><div className="grid grid-cols-2 md:grid-cols-4 gap-4"><StatCard title="Total Drugs" value={stats?.total_drugs} icon="💊" color="bg-blue-50 text-blue-900"/><StatCard title="Batches" value={stats?.total_batches} icon="📦" color="bg-green-50 text-green-900"/><StatCard title="Verifications" value={stats?.total_verifications} icon="✅" color="bg-purple-50 text-purple-900"/><StatCard title="Alerts" value={stats?.unresolved_alerts} icon="🚨" color="bg-red-50 text-red-900"/></div><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div className="bg-white rounded-2xl p-6 shadow-sm"><h3 className="font-semibold text-gray-900 mb-4">Verification Results</h3>{stats&&<div className="space-y-4">{[{label:"Authentic",value:stats.authentic_verifications,color:"bg-green-500"},{label:"Not Found",value:stats.not_found_verifications,color:"bg-yellow-500"},{label:"Counterfeit",value:stats.counterfeit_verifications,color:"bg-red-500"}].map((it,i)=>(<div key={i}><div className="flex justify-between text-sm mb-1"><span className="text-gray-600">{it.label}</span><span className="font-semibold">{it.value}</span></div><div className="h-2 bg-gray-100 rounded-full"><div className={"h-2 rounded-full "+it.color} style={{width:stats.total_verifications>0?(it.value/stats.total_verifications*100)+"%":"0%"}}></div></div></div>))}</div>}</div><div className="bg-white rounded-2xl p-6 shadow-sm"><h3 className="font-semibold text-gray-900 mb-4">Quick Actions</h3><div className="space-y-3"><button onClick={()=>{setShowAddDrug(true);setActive("drugs");}} className="w-full bg-primary-700 text-white py-3 rounded-xl font-medium hover:bg-primary-800 transition">+ Add New Drug</button><button onClick={()=>navTo("batches")} className="w-full border border-gray-200 text-gray-700 py-3 rounded-xl hover:bg-gray-50 transition">Manage Batches</button><button onClick={()=>navTo("qrcodes")} className="w-full border border-gray-200 text-gray-700 py-3 rounded-xl hover:bg-gray-50 transition">View QR Codes</button></div></div></div></div>)}
        {active==="drugs"&&(<div className="space-y-4"><div className="flex justify-end"><button onClick={()=>setShowAddDrug(true)} className="bg-primary-700 text-white px-6 py-2 rounded-xl font-medium hover:bg-primary-800">+ Add Drug</button></div>{showAddDrug&&(<div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"><motion.div initial={{scale:0.9,opacity:0}} animate={{scale:1,opacity:1}} className="bg-white rounded-2xl p-6 w-full max-w-md"><h2 className="text-xl font-bold mb-4">Add New Drug</h2><form onSubmit={handleAddDrug} className="space-y-3">{[["name","Drug Name"],["generic_name","Generic Name"],["nafdac_number","NAFDAC Number"],["dosage_form","Dosage Form"],["strength","Strength"]].map(([key,label])=>(<div key={key}><label className="block text-sm font-medium text-gray-700 mb-1">{label}</label><input value={drugForm[key]} onChange={e=>setDrugForm({...drugForm,[key]:e.target.value})} required={key!=="generic_name"} className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary-500" /></div>))}<div><label className="block text-sm font-medium text-gray-700 mb-1">Description</label><textarea value={drugForm.description} onChange={e=>setDrugForm({...drugForm,description:e.target.value})} className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary-500" rows="2"/></div><div className="flex gap-3 pt-2"><button type="button" onClick={()=>setShowAddDrug(false)} className="flex-1 border border-gray-300 py-2 rounded-lg hover:bg-gray-50">Cancel</button><button type="submit" disabled={loading} className="flex-1 bg-primary-700 text-white py-2 rounded-lg disabled:opacity-50">{loading?"Saving...":"Add Drug"}</button></div></form></motion.div></div>)}<div className="grid grid-cols-1 gap-4">{drugs.map(drug=>(<motion.div key={drug.id} initial={{opacity:0}} animate={{opacity:1}} className="bg-white rounded-2xl p-5 shadow-sm flex justify-between items-center"><div><h3 className="font-semibold text-gray-900">{drug.name}{drug.generic_name&&<span className="text-gray-400 font-normal"> ({drug.generic_name})</span>}</h3><p className="text-sm text-gray-500 mt-1">NAFDAC: {drug.nafdac_number} | {drug.dosage_form} {drug.strength}</p><span className={"text-xs px-2 py-1 rounded-full mt-2 inline-block "+(drug.status==="active"?"bg-green-100 text-green-700":"bg-red-100 text-red-700")}>{drug.status}</span></div><button onClick={()=>{setSelectedDrug(drug);fetchBatches(drug.id);setActive("batches");}} className="border border-gray-200 px-4 py-2 rounded-lg text-sm hover:bg-gray-50">Batches</button></motion.div>))}{drugs.length===0&&<div className="text-center text-gray-400 py-16"><div className="text-5xl mb-4">💊</div><p>No drugs yet. Add your first drug.</p></div>}</div></div>)}
        {active==="batches"&&(<div className="space-y-4">{selectedDrug?(<><div className="flex justify-between items-center"><p className="text-gray-600">Batches for <strong>{selectedDrug.name}</strong></p><button onClick={()=>setShowAddBatch(true)} className="bg-primary-700 text-white px-6 py-2 rounded-xl hover:bg-primary-800">+ Add Batch</button></div>{showAddBatch&&(<div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"><motion.div initial={{scale:0.9,opacity:0}} animate={{scale:1,opacity:1}} className="bg-white rounded-2xl p-6 w-full max-w-md"><h2 className="text-xl font-bold mb-4">Add Batch</h2><form onSubmit={handleAddBatch} className="space-y-3">{[["batch_number","Batch Number","text"],["manufacture_date","Manufacture Date","date"],["expiry_date","Expiry Date","date"],["quantity","Quantity","number"]].map(([key,label,type])=>(<div key={key}><label className="block text-sm font-medium text-gray-700 mb-1">{label}</label><input type={type} value={batchForm[key]} onChange={e=>setBatchForm({...batchForm,[key]:e.target.value})} required className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary-500"/></div>))}<div className="flex gap-3 pt-2"><button type="button" onClick={()=>setShowAddBatch(false)} className="flex-1 border border-gray-300 py-2 rounded-lg">Cancel</button><button type="submit" disabled={loading} className="flex-1 bg-primary-700 text-white py-2 rounded-lg disabled:opacity-50">{loading?"Saving...":"Add Batch"}</button></div></form></motion.div></div>)}<div className="grid grid-cols-1 gap-4">{batches.map(batch=>(<motion.div key={batch.id} initial={{opacity:0}} animate={{opacity:1}} className="bg-white rounded-2xl p-5 shadow-sm flex justify-between items-center"><div><h3 className="font-semibold text-gray-900">Batch: {batch.batch_number}</h3><p className="text-sm text-gray-500 mt-1">Mfg: {batch.manufacture_date} | Exp: {batch.expiry_date} | Qty: {batch.quantity}</p><span className={"text-xs px-2 py-1 rounded-full mt-2 inline-block "+(batch.is_expired?"bg-red-100 text-red-700":"bg-green-100 text-green-700")}>{batch.is_expired?"Expired":batch.status}</span></div><button onClick={()=>handleGetQR(batch)} className="bg-primary-700 text-white px-4 py-2 rounded-lg text-sm hover:bg-primary-800">Get QR</button></motion.div>))}{batches.length===0&&<div className="text-center text-gray-400 py-12"><div className="text-5xl mb-4">📦</div><p>No batches yet.</p></div>}</div></>):(<div className="text-center text-gray-400 py-16"><div className="text-5xl mb-4">📦</div><p>Select a drug first</p><button onClick={()=>navTo("drugs")} className="mt-4 bg-primary-700 text-white px-6 py-2 rounded-xl text-sm">Go to My Drugs</button></div>)}</div>)}
        {active==="qrcodes"&&(<div>{qrImage?(<motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="bg-white rounded-2xl p-8 shadow-sm flex flex-col items-center gap-6 max-w-md mx-auto"><h3 className="font-semibold text-xl">QR Code: {qrBatch}</h3><img src={"data:image/png;base64,"+qrImage} alt="QR" className="w-64 h-64 border rounded-xl p-2"/><p className="text-gray-500 text-sm text-center">Print and attach to drug packaging</p><a href={"data:image/png;base64,"+qrImage} download={"qr-"+qrBatch+".png"} className="bg-primary-700 text-white px-8 py-3 rounded-xl w-full text-center hover:bg-primary-800">Download QR Code</a><button onClick={()=>{setQrImage(null);setActive("batches");}} className="text-gray-400 text-sm">Back to Batches</button></motion.div>):(<div className="text-center text-gray-400 py-16"><div className="text-6xl mb-4">🔲</div><p>No QR generated yet</p><button onClick={()=>navTo("batches")} className="mt-4 bg-primary-700 text-white px-6 py-2 rounded-xl text-sm">Go to Batches</button></div>)}</div>)}
        {active==="supplychain"&&(<div className="bg-white rounded-2xl p-6 shadow-sm text-center text-gray-400 py-12"><div className="text-5xl mb-4">🔗</div><p>Supply chain visualization coming soon.</p></div>)}
      </div>
    </div>
  );
}
""")
print('Done')
