with open('src/utils/api.js', 'w', encoding='utf-8') as f:
    f.write('import axios from "axios";\n\n')
    f.write('const API = axios.create({\n')
    f.write('  baseURL: "http://127.0.0.1:8000/api",\n')
    f.write('});\n\n')
    f.write('API.interceptors.request.use((config) => {\n')
    f.write('  const token = localStorage.getItem("access_token");\n')
    f.write('  if (token) {\n')
    f.write('    config.headers.Authorization = "Bearer " + token;\n')
    f.write('  }\n')
    f.write('  return config;\n')
    f.write('});\n\n')
    f.write('API.interceptors.response.use(\n')
    f.write('  (response) => response,\n')
    f.write('  async (error) => {\n')
    f.write('    if (error.response?.status === 401) {\n')
    f.write('      const refresh = localStorage.getItem("refresh_token");\n')
    f.write('      if (refresh) {\n')
    f.write('        try {\n')
    f.write('          const res = await axios.post("http://127.0.0.1:8000/api/auth/token/refresh/", { refresh });\n')
    f.write('          localStorage.setItem("access_token", res.data.access);\n')
    f.write('          error.config.headers.Authorization = "Bearer " + res.data.access;\n')
    f.write('          return API(error.config);\n')
    f.write('        } catch {\n')
    f.write('          localStorage.clear();\n')
    f.write('          window.location.href = "/login";\n')
    f.write('        }\n')
    f.write('      }\n')
    f.write('    }\n')
    f.write('    return Promise.reject(error);\n')
    f.write('  }\n')
    f.write(');\n\n')
    f.write('export default API;\n')
print('Done')
