with open('src/pages/ManufacturerDashboard.jsx', 'w', encoding='utf-8') as f:
    f.write('import { useState, useEffect } from "react";\n')
    f.write('import { motion } from "framer-motion";\n')
    f.write('import DashboardLayout from "../components/layout/DashboardLayout";\n')
    f.write('import API from "../utils/api";\n')
    f.write('import { useAuth } from "../context/AuthContext";\n')
    f.write('import { Pill, Package, Search, AlertTriangle, Plus, X, TrendingUp } from "lucide-react";\n\n')
    f.write('function StatCard({ title, value, icon: Icon, gradient, delay }) {\n')
    f.write('  return (\n')
    f.write('    <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay}} className={"relative overflow-hidden rounded-2xl p-6 text-white shadow-lg " + gradient}>\n')
    f.write('      <div className="absolute -top-4 -right-4 w-24 h-24 bg-white bg-opacity-10 rounded-full"></div>\n')
    f.write('      <div className="absolute -bottom-6 -left-6 w-32 h-32 bg-white bg-opacity-5 rounded-full"></div>\n')
    f.write('      <div className="relative">\n')
    f.write('        <div className="w-10 h-10 bg-white bg-opacity-20 rounded-xl flex items-center justify-center mb-4"><Icon className="w-5 h-5 text-white" /></div>\n')
    f.write('        <p className="text-sm font-medium text-white text-opacity-80 mb-1">{title}</p>\n')
    f.write('        <p className="text-4xl font-extrabold">{value}</p>\n')
    f.write('      </div>\n')
    f.write('    </motion.div>\n')
    f.write('  );\n')
    f.write('}\n\n')
    f.write('export default function ManufacturerDashboard() {\n')
    f.write('  const { user } = useAuth();\n')
    f.write('  const [drugs, setDrugs] = useState([]);\n')
    f.write('  const [stats, setStats] = useState({});\n')
    f.write('  const [loading, setLoading] = useState(true);\n')
    f.write('  const [showAdd, setShowAdd] = useState(false);\n')
    f.write('  const [form, setForm] = useState({ name: "", generic_name: "", nafdac_number: "", description: "", dosage_form: "", strength: "" });\n')
    f.write('  const [error, setError] = useState("");\n')
    f.write('  const [saving, setSaving] = useState(false);\n\n')
    f.write('  useEffect(() => { fetchData(); }, []);\n\n')
    f.write('  const fetchData = async () => {\n')
    f.write('    try {\n')
    f.write('      const [d, s] = await Promise.all([API.get("/drugs/"), API.get("/analytics/dashboard/")]);\n')
    f.write('      setDrugs(d.data); setStats(s.data);\n')
    f.write('    } catch(e) { console.error(e); }\n')
    f.write('    finally { setLoading(false); }\n')
    f.write('  };\n\n')
    f.write('  const handleAdd = async (e) => {\n')
    f.write('    e.preventDefault(); setSaving(true); setError("");\n')
    f.write('    try {\n')
    f.write('      await API.post("/drugs/", form);\n')
    f.write('      setShowAdd(false);\n')
    f.write('      setForm({ name: "", generic_name: "", nafdac_number: "", description: "", dosage_form: "", strength: "" });\n')
    f.write('      fetchData();\n')
    f.write('    } catch(e) { setError(e.response?.data?.nafdac_number?.[0] || "Failed to add drug"); }\n')
    f.write('    finally { setSaving(false); }\n')
    f.write('  };\n\n')
    f.write('  if (loading) return <DashboardLayout title="Dashboard"><div className="flex items-center justify-center h-64"><div className="animate-spin rounded-full h-10 w-10 border-4 border-gray-200 border-t-primary-700"></div></div></DashboardLayout>;\n\n')
    f.write('  return (\n')
    f.write('    <DashboardLayout title={"Welcome, " + (user?.company_name || user?.email)} subtitle="Manage your drugs, batches and monitor verifications">\n\n')
    f.write('      <div className="grid grid-cols-2 lg:grid-cols-4 gap-5 mb-8">\n')
    f.write('        <StatCard title="Total Drugs" value={stats.total_drugs ?? 0} icon={Pill} gradient="bg-gradient-to-br from-[#0A2647] to-[#2E86C1]" delay={0} />\n')
    f.write('        <StatCard title="Total Batches" value={stats.total_batches ?? 0} icon={Package} gradient="bg-gradient-to-br from-emerald-600 to-emerald-400" delay={0.1} />\n')
    f.write('        <StatCard title="Verifications" value={stats.total_verifications ?? 0} icon={TrendingUp} gradient="bg-gradient-to-br from-violet-600 to-violet-400" delay={0.2} />\n')
    f.write('        <StatCard title="Active Alerts" value={stats.unresolved_alerts ?? 0} icon={AlertTriangle} gradient="bg-gradient-to-br from-rose-600 to-rose-400" delay={0.3} />\n')
    f.write('      </div>\n\n')
    f.write('      <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:0.4}} className="bg-white rounded-2xl shadow-sm border border-gray-100">\n')
    f.write('        <div className="flex justify-between items-center p-6 border-b border-gray-100">\n')
    f.write('          <div>\n')
    f.write('            <h2 className="text-lg font-bold text-gray-900">My Drugs</h2>\n')
    f.write('            <p className="text-sm text-gray-400 mt-0.5">{drugs.length} drug{drugs.length !== 1 ? "s" : ""} registered</p>\n')
    f.write('          </div>\n')
    f.write('          <button onClick={() => setShowAdd(!showAdd)} className="flex items-center gap-2 bg-[#0A2647] text-white px-5 py-2.5 rounded-xl hover:bg-[#1B4F72] transition font-medium text-sm shadow-sm">\n')
    f.write('            {showAdd ? <X className="w-4 h-4" /> : <Plus className="w-4 h-4" />}\n')
    f.write('            {showAdd ? "Cancel" : "Add Drug"}\n')
    f.write('          </button>\n')
    f.write('        </div>\n\n')
    f.write('        {showAdd && (\n')
    f.write('          <motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} className="border-b border-gray-100 p-6 bg-blue-50">\n')
    f.write('            <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2"><Plus className="w-4 h-4" /> Add New Drug</h3>\n')
    f.write('            {error && <div className="bg-red-50 border border-red-100 text-red-600 px-4 py-2 rounded-lg mb-4 text-sm">{error}</div>}\n')
    f.write('            <form onSubmit={handleAdd} className="grid grid-cols-1 md:grid-cols-2 gap-4">\n')
    f.write('              {[["name","Drug Name",true],["generic_name","Generic Name",false],["nafdac_number","NAFDAC Number",true],["dosage_form","Dosage Form",true],["strength","Strength",true],["description","Description",false]].map(([key,label,req]) => (\n')
    f.write('                <div key={key} className={key === "description" ? "md:col-span-2" : ""}>\n')
    f.write('                  <label className="block text-xs font-semibold text-gray-600 mb-1 uppercase tracking-wide">{label}{req && <span className="text-red-400 ml-1">*</span>}</label>\n')
    f.write('                  <input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} required={req} className="w-full border border-gray-200 bg-white rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 transition" />\n')
    f.write('                </div>\n')
    f.write('              ))}\n')
    f.write('              <div className="md:col-span-2 flex gap-3 pt-2">\n')
    f.write('                <button type="submit" disabled={saving} className="bg-[#0A2647] text-white px-6 py-2.5 rounded-xl hover:bg-[#1B4F72] transition font-medium text-sm disabled:opacity-50">{saving ? "Saving..." : "Save Drug"}</button>\n')
    f.write('                <button type="button" onClick={() => setShowAdd(false)} className="border border-gray-200 px-6 py-2.5 rounded-xl hover:bg-gray-50 transition text-sm text-gray-600">Cancel</button>\n')
    f.write('              </div>\n')
    f.write('            </form>\n')
    f.write('          </motion.div>\n')
    f.write('        )}\n\n')
    f.write('        <div className="overflow-x-auto">\n')
    f.write('          {drugs.length === 0 ? (\n')
    f.write('            <div className="flex flex-col items-center justify-center py-20 text-gray-400">\n')
    f.write('              <Pill className="w-16 h-16 text-gray-200 mb-4" />\n')
    f.write('              <p className="font-semibold text-gray-500 text-lg">No drugs registered yet</p>\n')
    f.write('              <p className="text-sm mt-1">Click Add Drug to register your first drug</p>\n')
    f.write('            </div>\n')
    f.write('          ) : (\n')
    f.write('            <table className="w-full text-sm">\n')
    f.write('              <thead>\n')
    f.write('                <tr className="bg-gray-50 border-b border-gray-100">\n')
    f.write('                  {["Drug Name","Generic Name","NAFDAC No.","Dosage Form","Strength","Status","Batches"].map(h => <th key={h} className="text-left py-3 px-5 text-xs font-semibold text-gray-400 uppercase tracking-wider">{h}</th>)}\n')
    f.write('                </tr>\n')
    f.write('              </thead>\n')
    f.write('              <tbody className="divide-y divide-gray-50">\n')
    f.write('                {drugs.map(drug => (\n')
    f.write('                  <tr key={drug.id} className="hover:bg-gray-50 transition">\n')
    f.write('                    <td className="py-4 px-5 font-semibold text-gray-900">{drug.name}</td>\n')
    f.write('                    <td className="py-4 px-5 text-gray-500">{drug.generic_name || "-"}</td>\n')
    f.write('                    <td className="py-4 px-5 font-mono text-xs text-gray-500 bg-gray-50">{drug.nafdac_number}</td>\n')
    f.write('                    <td className="py-4 px-5 text-gray-500">{drug.dosage_form}</td>\n')
    f.write('                    <td className="py-4 px-5 text-gray-500">{drug.strength}</td>\n')
    f.write('                    <td className="py-4 px-5"><span className={"px-3 py-1 rounded-full text-xs font-semibold " + (drug.status === "active" ? "bg-emerald-50 text-emerald-700 border border-emerald-200" : "bg-red-50 text-red-700 border border-red-200")}>{drug.status}</span></td>\n')
    f.write('                    <td className="py-4 px-5 text-gray-500 font-semibold">{drug.batches?.length || 0}</td>\n')
    f.write('                  </tr>\n')
    f.write('                ))}\n')
    f.write('              </tbody>\n')
    f.write('            </table>\n')
    f.write('          )}\n')
    f.write('        </div>\n')
    f.write('      </motion.div>\n')
    f.write('    </DashboardLayout>\n')
    f.write('  );\n')
    f.write('}\n')
print('Done')
