with open('src/pages/PatientPage.jsx', 'w', encoding='utf-8') as f:
    f.write('import { useState } from "react";\n')
    f.write('import { motion } from "framer-motion";\n')
    f.write('import DashboardLayout from "../components/layout/DashboardLayout";\n')
    f.write('import API from "../utils/api";\n')
    f.write('import { Search, CheckCircle, XCircle, AlertTriangle, Clock, Shield } from "lucide-react";\n\n')
    f.write('export default function PatientPage() {\n')
    f.write('  const [code, setCode] = useState("");\n')
    f.write('  const [result, setResult] = useState(null);\n')
    f.write('  const [loading, setLoading] = useState(false);\n')
    f.write('  const [error, setError] = useState("");\n\n')
    f.write('  const handleVerify = async (e) => {\n')
    f.write('    e.preventDefault(); setLoading(true); setError(""); setResult(null);\n')
    f.write('    try { const res = await API.post("/verification/verify/", { scanned_code: code }); setResult(res.data); }\n')
    f.write('    catch { setError("Verification failed. Please try again."); }\n')
    f.write('    finally { setLoading(false); }\n')
    f.write('  };\n\n')
    f.write('  const resultConfig = {\n')
    f.write('    authentic: { bg: "bg-emerald-50 border-emerald-300", icon: CheckCircle, iconColor: "text-emerald-500", title: "Drug is Authentic", msg: "This drug is genuine and safe to use.", text: "text-emerald-800" },\n')
    f.write('    not_found: { bg: "bg-red-50 border-red-300", icon: XCircle, iconColor: "text-red-500", title: "Drug Not Found", msg: "This drug could not be verified. Do not use!", text: "text-red-800" },\n')
    f.write('    expired: { bg: "bg-amber-50 border-amber-300", icon: Clock, iconColor: "text-amber-500", title: "Drug is Expired", msg: "This drug has expired. Do not use!", text: "text-amber-800" },\n')
    f.write('    recalled: { bg: "bg-orange-50 border-orange-300", icon: AlertTriangle, iconColor: "text-orange-500", title: "Drug is Recalled", msg: "This drug has been recalled. Return to pharmacy!", text: "text-orange-800" },\n')
    f.write('    counterfeit: { bg: "bg-red-100 border-red-500", icon: XCircle, iconColor: "text-red-600", title: "Counterfeit Detected", msg: "WARNING: This is a counterfeit drug. Do not use!", text: "text-red-900" },\n')
    f.write('  };\n\n')
    f.write('  const config = result ? (resultConfig[result.result] || resultConfig.not_found) : null;\n\n')
    f.write('  return (\n')
    f.write('    <DashboardLayout title="Verify Your Drug" subtitle="Enter the batch number from your drug packaging to verify authenticity">\n')
    f.write('      <div className="max-w-xl mx-auto">\n')
    f.write('        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-8 mb-6">\n')
    f.write('          <div className="flex items-center justify-center w-16 h-16 bg-primary-100 rounded-2xl mx-auto mb-6"><Shield className="w-8 h-8 text-primary-700" /></div>\n')
    f.write('          <h2 className="text-xl font-bold text-gray-900 text-center mb-2">Drug Verification</h2>\n')
    f.write('          <p className="text-gray-400 text-center text-sm mb-8">Enter the batch number printed on your drug packaging</p>\n')
    f.write('          <form onSubmit={handleVerify} className="space-y-4">\n')
    f.write('            <input value={code} onChange={e=>setCode(e.target.value)} required placeholder="Enter batch number e.g. BATCH-001" className="w-full border-2 border-gray-200 rounded-xl px-5 py-4 text-center text-lg font-mono tracking-widest focus:outline-none focus:border-primary-500 transition" />\n')
    f.write('            {error && <div className="bg-red-50 text-red-600 border border-red-100 px-4 py-3 rounded-xl text-sm text-center">{error}</div>}\n')
    f.write('            <button type="submit" disabled={loading} className="w-full bg-[#0A2647] text-white py-4 rounded-xl font-bold text-lg hover:bg-[#1B4F72] transition disabled:opacity-50 flex items-center justify-center gap-2">\n')
    f.write('              <Search className="w-5 h-5" />\n')
    f.write('              {loading ? "Checking..." : "Verify Drug"}\n')
    f.write('            </button>\n')
    f.write('          </form>\n')
    f.write('        </div>\n\n')
    f.write('        {result && config && (\n')
    f.write('          <motion.div initial={{opacity:0,scale:0.95}} animate={{opacity:1,scale:1}} className={"border-2 rounded-2xl p-8 text-center " + config.bg}>\n')
    f.write('            <config.icon className={"w-16 h-16 mx-auto mb-4 " + config.iconColor} />\n')
    f.write('            <h3 className={"text-2xl font-extrabold mb-2 " + config.text}>{config.title}</h3>\n')
    f.write('            <p className={"text-lg mb-4 " + config.text}>{config.msg}</p>\n')
    f.write('            {result.batch && <p className={"text-sm font-medium opacity-70 " + config.text}>{result.batch}</p>}\n')
    f.write('          </motion.div>\n')
    f.write('        )}\n')
    f.write('      </div>\n')
    f.write('    </DashboardLayout>\n')
    f.write('  );\n')
    f.write('}\n')
print('Done')
