with open('src/pages/LandingPage.jsx', 'w', encoding='utf-8') as f:
    f.write('import { useState, useEffect } from "react";\n')
    f.write('import { motion } from "framer-motion";\n')
    f.write('import { useNavigate } from "react-router-dom";\n')
    f.write('import { Shield, QrCode, Package, Bell, BarChart2, Users, ChevronRight, CheckCircle, Menu, X } from "lucide-react";\n\n')
    f.write('const features = [\n')
    f.write('  { icon: Shield, title: "Instant Verification", desc: "Verify drug authenticity in seconds using QR codes and HMAC signatures", color: "text-blue-600 bg-blue-50" },\n')
    f.write('  { icon: Package, title: "Supply Chain Tracking", desc: "Track every drug from manufacturer to pharmacy with full transparency", color: "text-emerald-600 bg-emerald-50" },\n')
    f.write('  { icon: Bell, title: "Counterfeit Alerts", desc: "Real-time alerts when counterfeit or recalled drugs are detected", color: "text-red-600 bg-red-50" },\n')
    f.write('  { icon: BarChart2, title: "Analytics Dashboard", desc: "Detailed reports and insights for regulators and manufacturers", color: "text-purple-600 bg-purple-50" },\n')
    f.write('  { icon: QrCode, title: "QR Code Generation", desc: "Cryptographically signed QR codes for every batch number", color: "text-amber-600 bg-amber-50" },\n')
    f.write('  { icon: Users, title: "Multi-Role Access", desc: "Tailored dashboards for manufacturers, pharmacists, regulators and patients", color: "text-pink-600 bg-pink-50" },\n')
    f.write('];\n\n')
    f.write('const steps = [\n')
    f.write('  { num: "01", title: "Scan QR Code", desc: "Use your phone camera to scan the QR code on the drug packaging", img: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=500&q=80" },\n')
    f.write('  { num: "02", title: "Instant Verification", desc: "Our system verifies the cryptographic signature and checks the database instantly", img: "https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=500&q=80" },\n')
    f.write('  { num: "03", title: "Get Clear Results", desc: "Immediately know if the drug is authentic, expired, recalled or counterfeit", img: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&q=80" },\n')
    f.write('];\n\n')
    f.write('const stats = [\n')
    f.write('  { value: "10M+", label: "Drugs Verified" },\n')
    f.write('  { value: "500+", label: "Manufacturers" },\n')
    f.write('  { value: "99.9%", label: "Accuracy Rate" },\n')
    f.write('  { value: "24/7", label: "Monitoring" },\n')
    f.write('];\n\n')
    f.write('export default function LandingPage() {\n')
    f.write('  const navigate = useNavigate();\n')
    f.write('  const [scrolled, setScrolled] = useState(false);\n')
    f.write('  const [menuOpen, setMenuOpen] = useState(false);\n\n')
    f.write('  useEffect(() => {\n')
    f.write('    const handleScroll = () => setScrolled(window.scrollY > 20);\n')
    f.write('    window.addEventListener("scroll", handleScroll);\n')
    f.write('    return () => window.removeEventListener("scroll", handleScroll);\n')
    f.write('  }, []);\n\n')
    f.write('  return (\n')
    f.write('    <div className="min-h-screen bg-white">\n\n')
    f.write('      {/* Navbar */}\n')
    f.write('      <nav className={"fixed top-0 left-0 right-0 z-50 transition-all duration-300 " + (scrolled ? "bg-white shadow-md" : "bg-transparent")}>\n')
    f.write('        <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">\n')
    f.write('          <div className="flex items-center gap-2">\n')
    f.write('            <Shield className={"w-7 h-7 " + (scrolled ? "text-primary-700" : "text-white")} />\n')
    f.write('            <span className={"text-xl font-bold " + (scrolled ? "text-primary-900" : "text-white")}>DrugVerify</span>\n')
    f.write('          </div>\n')
    f.write('          <div className="hidden md:flex items-center gap-8">\n')
    f.write('            {["Features", "How It Works", "Stats"].map(item => (\n')
    f.write('              <a key={item} href={"#" + item.toLowerCase().replace(" ","-")} className={"font-medium transition " + (scrolled ? "text-gray-600 hover:text-primary-700" : "text-white hover:text-blue-200")}>{item}</a>\n')
    f.write('            ))}\n')
    f.write('          </div>\n')
    f.write('          <div className="hidden md:flex items-center gap-3">\n')
    f.write('            <button onClick={() => navigate("/login")} className={"border font-medium px-5 py-2 rounded-lg transition " + (scrolled ? "border-primary-700 text-primary-700 hover:bg-primary-100" : "border-white text-white hover:bg-white hover:bg-opacity-10")}>Login</button>\n')
    f.write('            <button onClick={() => navigate("/register")} className="bg-white text-primary-900 font-bold px-5 py-2 rounded-lg hover:bg-blue-50 transition shadow-lg">Get Started</button>\n')
    f.write('          </div>\n')
    f.write('          <button onClick={() => setMenuOpen(!menuOpen)} className={"md:hidden " + (scrolled ? "text-gray-900" : "text-white")}>{menuOpen ? <X size={24} /> : <Menu size={24} />}</button>\n')
    f.write('        </div>\n')
    f.write('        {menuOpen && (\n')
    f.write('          <div className="md:hidden bg-white border-t px-6 py-4 space-y-3">\n')
    f.write('            <button onClick={() => navigate("/login")} className="w-full text-left text-gray-700 font-medium py-2">Login</button>\n')
    f.write('            <button onClick={() => navigate("/register")} className="w-full bg-primary-700 text-white font-medium px-5 py-2 rounded-lg">Get Started</button>\n')
    f.write('          </div>\n')
    f.write('        )}\n')
    f.write('      </nav>\n\n')
    f.write('      {/* Hero - Full screen background image with text overlay */}\n')
    f.write('      <div className="relative min-h-screen flex items-center">\n')
    f.write('        {/* Background Image */}\n')
    f.write('        <div className="absolute inset-0">\n')
    f.write('          <img src="https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=1600&q=90" alt="Doctor" className="w-full h-full object-cover object-center" />\n')
    f.write('          <div className="absolute inset-0 bg-gradient-to-r from-primary-900 via-primary-900 via-opacity-90 to-transparent"></div>\n')
    f.write('          <div className="absolute inset-0 bg-primary-900 bg-opacity-60"></div>\n')
    f.write('        </div>\n\n')
    f.write('        {/* Text Content */}\n')
    f.write('        <div className="relative max-w-7xl mx-auto px-6 py-32">\n')
    f.write('          <motion.div initial={{opacity:0,y:40}} animate={{opacity:1,y:0}} transition={{duration:0.8}} className="max-w-2xl">\n')
    f.write('            <div className="inline-flex items-center gap-2 bg-white bg-opacity-10 border border-white border-opacity-20 rounded-full px-4 py-2 mb-6">\n')
    f.write('              <CheckCircle className="w-4 h-4 text-green-400" />\n')
    f.write('              <span className="text-white text-sm font-medium">NAFDAC Certified Platform</span>\n')
    f.write('            </div>\n')
    f.write('            <h1 className="text-6xl font-extrabold text-white leading-tight mb-6">Verify Your Drugs,<br /><span className="text-green-400">Protect Your Life</span></h1>\n')
    f.write('            <p className="text-xl text-blue-100 mb-10 leading-relaxed max-w-xl">Scan any drug QR code instantly to verify authenticity, check expiry dates, and track the full supply chain from manufacturer to your hands.</p>\n')
    f.write('            <div className="flex flex-wrap gap-4 mb-12">\n')
    f.write('              <button onClick={() => navigate("/register")} className="flex items-center gap-2 bg-white text-primary-900 font-bold px-8 py-4 rounded-xl hover:bg-blue-50 transition shadow-xl text-lg">Get Started Free <ChevronRight className="w-5 h-5" /></button>\n')
    f.write('              <button onClick={() => navigate("/login")} className="flex items-center gap-2 border-2 border-white border-opacity-50 text-white font-semibold px-8 py-4 rounded-xl hover:bg-white hover:bg-opacity-10 transition text-lg">Sign In</button>\n')
    f.write('            </div>\n')
    f.write('            <div className="flex items-center gap-6">\n')
    f.write('              {[{v:"10M+",l:"Drugs Verified"},{v:"500+",l:"Manufacturers"},{v:"99.9%",l:"Accuracy"}].map((s,i) => (\n')
    f.write('                <div key={i} className="text-center">\n')
    f.write('                  <p className="text-3xl font-extrabold text-white">{s.v}</p>\n')
    f.write('                  <p className="text-blue-300 text-sm">{s.l}</p>\n')
    f.write('                </div>\n')
    f.write('              ))}\n')
    f.write('            </div>\n')
    f.write('          </motion.div>\n')
    f.write('        </div>\n')
    f.write('      </div>\n\n')
    f.write('      {/* Features */}\n')
    f.write('      <div id="features" className="py-24 bg-gray-50">\n')
    f.write('        <div className="max-w-7xl mx-auto px-6">\n')
    f.write('          <motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} className="text-center mb-16">\n')
    f.write('            <h2 className="text-4xl font-extrabold text-gray-900">Everything You Need</h2>\n')
    f.write('            <p className="text-gray-500 mt-3 text-lg max-w-2xl mx-auto">A complete drug verification ecosystem built for healthcare professionals and patients</p>\n')
    f.write('          </motion.div>\n')
    f.write('          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">\n')
    f.write('            {features.map((feat, i) => (\n')
    f.write('              <motion.div key={i} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} transition={{delay:i*0.1}} className="bg-white rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow border border-gray-100">\n')
    f.write('                <div className={"w-12 h-12 rounded-xl flex items-center justify-center mb-4 " + feat.color}><feat.icon className="w-6 h-6" /></div>\n')
    f.write('                <h3 className="text-lg font-bold text-gray-900 mb-2">{feat.title}</h3>\n')
    f.write('                <p className="text-gray-500 leading-relaxed">{feat.desc}</p>\n')
    f.write('              </motion.div>\n')
    f.write('            ))}\n')
    f.write('          </div>\n')
    f.write('        </div>\n')
    f.write('      </div>\n\n')
    f.write('      {/* Stats */}\n')
    f.write('      <div id="stats" className="bg-primary-900 py-16">\n')
    f.write('        <div className="max-w-5xl mx-auto px-6 grid grid-cols-2 md:grid-cols-4 gap-8 text-center">\n')
    f.write('          {stats.map((s, i) => (\n')
    f.write('            <motion.div key={i} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} transition={{delay:i*0.1}}>\n')
    f.write('              <p className="text-4xl font-extrabold text-white">{s.value}</p>\n')
    f.write('              <p className="text-blue-300 mt-1 font-medium">{s.label}</p>\n')
    f.write('            </motion.div>\n')
    f.write('          ))}\n')
    f.write('        </div>\n')
    f.write('      </div>\n\n')
    f.write('      {/* How It Works */}\n')
    f.write('      <div id="how-it-works" className="py-24 bg-white">\n')
    f.write('        <div className="max-w-7xl mx-auto px-6">\n')
    f.write('          <motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} className="text-center mb-16">\n')
    f.write('            <h2 className="text-4xl font-extrabold text-gray-900">How It Works</h2>\n')
    f.write('            <p className="text-gray-500 mt-3 text-lg">Three simple steps to verify any drug</p>\n')
    f.write('          </motion.div>\n')
    f.write('          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">\n')
    f.write('            {steps.map((step, i) => (\n')
    f.write('              <motion.div key={i} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} transition={{delay:i*0.2}} className="bg-gray-50 rounded-3xl overflow-hidden border border-gray-100">\n')
    f.write('                <img src={step.img} alt={step.title} className="w-full h-52 object-cover" />\n')
    f.write('                <div className="p-6">\n')
    f.write('                  <span className="text-5xl font-extrabold text-blue-100">{step.num}</span>\n')
    f.write('                  <h3 className="text-xl font-bold text-gray-900 mt-2 mb-2">{step.title}</h3>\n')
    f.write('                  <p className="text-gray-500">{step.desc}</p>\n')
    f.write('                </div>\n')
    f.write('              </motion.div>\n')
    f.write('            ))}\n')
    f.write('          </div>\n')
    f.write('        </div>\n')
    f.write('      </div>\n\n')
    f.write('      {/* CTA */}\n')
    f.write('      <div className="relative py-24">\n')
    f.write('        <img src="https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=1600&q=80" alt="Hospital" className="absolute inset-0 w-full h-full object-cover" />\n')
    f.write('        <div className="absolute inset-0 bg-primary-900 bg-opacity-80"></div>\n')
    f.write('        <motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} className="relative max-w-3xl mx-auto text-center px-6">\n')
    f.write('          <h2 className="text-4xl font-extrabold text-white mb-4">Ready to Protect Lives?</h2>\n')
    f.write('          <p className="text-blue-200 text-lg mb-10">Join thousands of healthcare professionals using DrugVerify to combat counterfeit drugs in Nigeria</p>\n')
    f.write('          <button onClick={() => navigate("/register")} className="inline-flex items-center gap-2 bg-white text-primary-900 font-bold px-10 py-4 rounded-xl hover:bg-blue-50 transition shadow-xl text-lg">Create Free Account <ChevronRight className="w-5 h-5" /></button>\n')
    f.write('        </motion.div>\n')
    f.write('      </div>\n\n')
    f.write('      {/* Footer */}\n')
    f.write('      <footer className="bg-gray-900 text-gray-400 py-8 text-center">\n')
    f.write('        <div className="flex items-center justify-center gap-2 mb-2">\n')
    f.write('          <Shield className="w-5 h-5 text-primary-500" />\n')
    f.write('          <span className="text-white font-bold">DrugVerify</span>\n')
    f.write('        </div>\n')
    f.write('        <p className="text-sm">2026 DrugVerify. Powered by NAFDAC Drug Verification System. All rights reserved.</p>\n')
    f.write('      </footer>\n')
    f.write('    </div>\n')
    f.write('  );\n')
    f.write('}\n')
print('Done')
