with open('src/pages/RegisterPage.jsx', 'w', encoding='utf-8') as f:
    f.write('import { useState } from "react";\n')
    f.write('import { motion } from "framer-motion";\n')
    f.write('import { useNavigate, Link } from "react-router-dom";\n')
    f.write('import { useAuth } from "../context/AuthContext";\n\n')
    f.write('export default function RegisterPage() {\n')
    f.write('  const [form, setForm] = useState({ email: "", password: "", role: "patient", company_name: "", phone: "", license_number: "" });\n')
    f.write('  const [error, setError] = useState("");\n')
    f.write('  const [loading, setLoading] = useState(false);\n')
    f.write('  const { register } = useAuth();\n')
    f.write('  const navigate = useNavigate();\n\n')
    f.write('  const handleSubmit = async (e) => {\n')
    f.write('    e.preventDefault();\n')
    f.write('    setLoading(true);\n')
    f.write('    setError("");\n')
    f.write('    try {\n')
    f.write('      const user = await register(form);\n')
    f.write('      const routes = { manufacturer: "/manufacturer", pharmacist: "/pharmacist", regulator: "/regulator", patient: "/patient", wholesaler: "/pharmacist" };\n')
    f.write('      navigate(routes[user.role] || "/dashboard");\n')
    f.write('    } catch (err) {\n')
    f.write('      setError(err.response?.data?.email?.[0] || "Registration failed");\n')
    f.write('    } finally {\n')
    f.write('      setLoading(false);\n')
    f.write('    }\n')
    f.write('  };\n\n')
    f.write('  const roles = ["manufacturer", "wholesaler", "pharmacist", "regulator", "patient"];\n')
    f.write('  const showCompany = ["manufacturer", "wholesaler", "pharmacist"].includes(form.role);\n\n')
    f.write('  return (\n')
    f.write('    <div className="min-h-screen bg-gradient-to-br from-primary-900 to-primary-600 flex items-center justify-center px-4 py-8">\n')
    f.write('      <motion.div initial={{opacity:0,scale:0.9}} animate={{opacity:1,scale:1}} className="bg-white rounded-2xl shadow-2xl p-8 w-full max-w-md">\n')
    f.write('        <div className="text-center mb-8">\n')
    f.write('          <div className="text-4xl mb-2">💊</div>\n')
    f.write('          <h1 className="text-2xl font-bold text-primary-900">Create Account</h1>\n')
    f.write('          <p className="text-gray-500 mt-1">Join DrugVerify today</p>\n')
    f.write('        </div>\n')
    f.write('        {error && <div className="bg-red-50 text-red-600 px-4 py-3 rounded-lg mb-4 text-sm">{error}</div>}\n')
    f.write('        <form onSubmit={handleSubmit} className="space-y-4">\n')
    f.write('          <div>\n')
    f.write('            <label className="block text-sm font-medium text-gray-700 mb-1">Role</label>\n')
    f.write('            <select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-primary-500">\n')
    f.write('              {roles.map(r => <option key={r} value={r}>{r.charAt(0).toUpperCase()+r.slice(1)}</option>)}\n')
    f.write('            </select>\n')
    f.write('          </div>\n')
    f.write('          <div>\n')
    f.write('            <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>\n')
    f.write('            <input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-primary-500" placeholder="you@example.com" />\n')
    f.write('          </div>\n')
    f.write('          <div>\n')
    f.write('            <label className="block text-sm font-medium text-gray-700 mb-1">Password</label>\n')
    f.write('            <input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-primary-500" placeholder="min 8 characters" />\n')
    f.write('          </div>\n')
    f.write('          <div>\n')
    f.write('            <label className="block text-sm font-medium text-gray-700 mb-1">Phone</label>\n')
    f.write('            <input type="text" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-primary-500" placeholder="08012345678" />\n')
    f.write('          </div>\n')
    f.write('          {showCompany && (\n')
    f.write('            <>\n')
    f.write('              <div>\n')
    f.write('                <label className="block text-sm font-medium text-gray-700 mb-1">Company Name</label>\n')
    f.write('                <input type="text" value={form.company_name} onChange={e=>setForm({...form,company_name:e.target.value})} className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-primary-500" placeholder="Your company name" />\n')
    f.write('              </div>\n')
    f.write('              <div>\n')
    f.write('                <label className="block text-sm font-medium text-gray-700 mb-1">License Number</label>\n')
    f.write('                <input type="text" value={form.license_number} onChange={e=>setForm({...form,license_number:e.target.value})} className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-primary-500" placeholder="Your license number" />\n')
    f.write('              </div>\n')
    f.write('            </>\n')
    f.write('          )}\n')
    f.write('          <button type="submit" disabled={loading} className="w-full bg-primary-700 text-white py-3 rounded-lg font-semibold hover:bg-primary-800 transition disabled:opacity-50">\n')
    f.write('            {loading ? "Creating account..." : "Create Account"}\n')
    f.write('          </button>\n')
    f.write('        </form>\n')
    f.write('        <p className="text-center text-gray-500 mt-6 text-sm">Already have an account? <Link to="/login" className="text-primary-700 font-semibold hover:underline">Login</Link></p>\n')
    f.write('      </motion.div>\n')
    f.write('    </div>\n')
    f.write('  );\n')
    f.write('}\n')
print('Done')
