with open('src/components/layout/DashboardLayout.jsx', 'w', encoding='utf-8') as f:
    f.write('import Sidebar from "./Sidebar";\n')
    f.write('import { Bell, Search } from "lucide-react";\n')
    f.write('import { useAuth } from "../../context/AuthContext";\n\n')
    f.write('export default function DashboardLayout({ children, title, subtitle }) {\n')
    f.write('  const { user } = useAuth();\n')
    f.write('  return (\n')
    f.write('    <div className="flex min-h-screen bg-gray-50">\n')
    f.write('      <Sidebar />\n')
    f.write('      <div className="flex-1 flex flex-col overflow-hidden">\n')
    f.write('        <header className="bg-white border-b border-gray-100 px-8 py-4 flex items-center justify-between sticky top-0 z-10 shadow-sm">\n')
    f.write('          <div>\n')
    f.write('            {title && <h1 className="text-xl font-bold text-gray-900">{title}</h1>}\n')
    f.write('            {subtitle && <p className="text-sm text-gray-500 mt-0.5">{subtitle}</p>}\n')
    f.write('          </div>\n')
    f.write('          <div className="flex items-center gap-4">\n')
    f.write('            <div className="relative hidden md:block">\n')
    f.write('              <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />\n')
    f.write('              <input placeholder="Search..." className="pl-9 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary-500 w-48" />\n')
    f.write('            </div>\n')
    f.write('            <button className="relative p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-50 rounded-lg transition">\n')
    f.write('              <Bell className="w-5 h-5" />\n')
    f.write('              <span className="absolute top-1 right-1 w-2 h-2 bg-red-500 rounded-full"></span>\n')
    f.write('            </button>\n')
    f.write('            <div className="flex items-center gap-2">\n')
    f.write('              <div className="w-8 h-8 rounded-full bg-primary-700 flex items-center justify-center text-white text-sm font-bold">{user?.email?.[0]?.toUpperCase()}</div>\n')
    f.write('              <span className="text-sm font-medium text-gray-700 hidden md:block">{user?.company_name || user?.email}</span>\n')
    f.write('            </div>\n')
    f.write('          </div>\n')
    f.write('        </header>\n')
    f.write('        <main className="flex-1 overflow-auto p-8">{children}</main>\n')
    f.write('      </div>\n')
    f.write('    </div>\n')
    f.write('  );\n')
    f.write('}\n')
print('Done')
