with open('src/components/layout/Sidebar.jsx', 'w', encoding='utf-8') as f:
    f.write('import { NavLink, useNavigate } from "react-router-dom";\n')
    f.write('import { useAuth } from "../../context/AuthContext";\n')
    f.write('import { motion } from "framer-motion";\n\n')
    f.write('const menuItems = {\n')
    f.write('  manufacturer: [\n')
    f.write('    { path: "/manufacturer", label: "Dashboard", icon: "📊" },\n')
    f.write('    { path: "/manufacturer/drugs", label: "My Drugs", icon: "💊" },\n')
    f.write('    { path: "/manufacturer/batches", label: "Batches", icon: "📦" },\n')
    f.write('    { path: "/manufacturer/alerts", label: "Alerts", icon: "🚨" },\n')
    f.write('  ],\n')
    f.write('  pharmacist: [\n')
    f.write('    { path: "/pharmacist", label: "Dashboard", icon: "📊" },\n')
    f.write('    { path: "/pharmacist/verify", label: "Verify Drug", icon: "🔍" },\n')
    f.write('    { path: "/pharmacist/history", label: "History", icon: "📋" },\n')
    f.write('  ],\n')
    f.write('  regulator: [\n')
    f.write('    { path: "/regulator", label: "Dashboard", icon: "📊" },\n')
    f.write('    { path: "/regulator/drugs", label: "All Drugs", icon: "💊" },\n')
    f.write('    { path: "/regulator/alerts", label: "Alerts", icon: "🚨" },\n')
    f.write('    { path: "/regulator/analytics", label: "Analytics", icon: "📈" },\n')
    f.write('    { path: "/regulator/users", label: "Users", icon: "👥" },\n')
    f.write('  ],\n')
    f.write('  patient: [\n')
    f.write('    { path: "/patient", label: "Verify Drug", icon: "🔍" },\n')
    f.write('    { path: "/patient/history", label: "History", icon: "📋" },\n')
    f.write('  ],\n')
    f.write('};\n\n')
    f.write('const roleColors = { manufacturer: "from-blue-900 to-blue-700", pharmacist: "from-emerald-900 to-emerald-700", regulator: "from-purple-900 to-purple-700", patient: "from-rose-900 to-rose-700" };\n\n')
    f.write('export default function Sidebar() {\n')
    f.write('  const { user, logout } = useAuth();\n')
    f.write('  const navigate = useNavigate();\n')
    f.write('  const items = menuItems[user?.role] || [];\n')
    f.write('  const gradient = roleColors[user?.role] || "from-gray-900 to-gray-700";\n\n')
    f.write('  const handleLogout = () => { logout(); navigate("/login"); };\n\n')
    f.write('  return (\n')
    f.write('    <motion.div initial={{x:-20,opacity:0}} animate={{x:0,opacity:1}} className={"w-64 min-h-screen bg-gradient-to-b " + gradient + " text-white flex flex-col shadow-2xl"}>\n')
    f.write('      <div className="p-6 border-b border-white border-opacity-10">\n')
    f.write('        <div className="flex items-center gap-3 mb-6">\n')
    f.write('          <img src="https://cdn-icons-png.flaticon.com/512/2913/2913421.png" alt="logo" className="w-9 h-9" />\n')
    f.write('          <span className="text-xl font-bold tracking-wide">DrugVerify</span>\n')
    f.write('        </div>\n')
    f.write('        <div className="flex items-center gap-3 bg-white bg-opacity-10 rounded-xl p-3">\n')
    f.write('          <div className="w-10 h-10 rounded-full bg-white bg-opacity-20 flex items-center justify-center text-lg font-bold">{user?.email?.[0]?.toUpperCase()}</div>\n')
    f.write('          <div className="flex-1 min-w-0">\n')
    f.write('            <p className="text-sm font-medium truncate">{user?.company_name || user?.email}</p>\n')
    f.write('            <span className="text-xs text-white text-opacity-60 capitalize">{user?.role}</span>\n')
    f.write('          </div>\n')
    f.write('        </div>\n')
    f.write('      </div>\n\n')
    f.write('      <nav className="flex-1 p-4 space-y-1">\n')
    f.write('        <p className="text-xs text-white text-opacity-40 uppercase tracking-widest px-3 mb-3">Menu</p>\n')
    f.write('        {items.map((item) => (\n')
    f.write('          <NavLink key={item.path} to={item.path} end className={({isActive}) => "flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200 " + (isActive ? "bg-white bg-opacity-20 text-white shadow-lg" : "text-white text-opacity-60 hover:bg-white hover:bg-opacity-10 hover:text-white")}>\n')
    f.write('            <span className="text-lg">{item.icon}</span>\n')
    f.write('            <span className="font-medium">{item.label}</span>\n')
    f.write('          </NavLink>\n')
    f.write('        ))}\n')
    f.write('      </nav>\n\n')
    f.write('      <div className="p-4 border-t border-white border-opacity-10">\n')
    f.write('        <button onClick={handleLogout} className="w-full flex items-center gap-3 px-4 py-3 text-white text-opacity-60 hover:text-white hover:bg-white hover:bg-opacity-10 rounded-xl transition-all duration-200">\n')
    f.write('          <span className="text-lg">🚪</span>\n')
    f.write('          <span className="font-medium">Logout</span>\n')
    f.write('        </button>\n')
    f.write('      </div>\n')
    f.write('    </motion.div>\n')
    f.write('  );\n')
    f.write('}\n')
print('Done')
