with open('src/App.jsx', 'w', encoding='utf-8') as f:
    f.write('import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";\n')
    f.write('import { AuthProvider, useAuth } from "./context/AuthContext";\n')
    f.write('import LandingPage from "./pages/LandingPage";\n')
    f.write('import LoginPage from "./pages/LoginPage";\n')
    f.write('import RegisterPage from "./pages/RegisterPage";\n')
    f.write('import ManufacturerDashboard from "./pages/ManufacturerDashboard";\n')
    f.write('import PharmacistDashboard from "./pages/PharmacistDashboard";\n')
    f.write('import RegulatorDashboard from "./pages/RegulatorDashboard";\n')
    f.write('import PatientPage from "./pages/PatientPage";\n\n')
    f.write('const ProtectedRoute = ({ children, roles }) => {\n')
    f.write('  const { user, loading } = useAuth();\n')
    f.write('  if (loading) return <div className="flex items-center justify-center h-screen"><div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-700"></div></div>;\n')
    f.write('  if (!user) return <Navigate to="/login" />;\n')
    f.write('  if (roles && !roles.includes(user.role)) return <Navigate to="/login" />;\n')
    f.write('  return children;\n')
    f.write('};\n\n')
    f.write('const DashboardRedirect = () => {\n')
    f.write('  const { user } = useAuth();\n')
    f.write('  if (!user) return <Navigate to="/login" />;\n')
    f.write('  const routes = { manufacturer: "/manufacturer", pharmacist: "/pharmacist", regulator: "/regulator", patient: "/patient", wholesaler: "/pharmacist" };\n')
    f.write('  return <Navigate to={routes[user.role] || "/login"} />;\n')
    f.write('};\n\n')
    f.write('export default function App() {\n')
    f.write('  return (\n')
    f.write('    <AuthProvider>\n')
    f.write('      <BrowserRouter>\n')
    f.write('        <Routes>\n')
    f.write('          <Route path="/" element={<LandingPage />} />\n')
    f.write('          <Route path="/login" element={<LoginPage />} />\n')
    f.write('          <Route path="/register" element={<RegisterPage />} />\n')
    f.write('          <Route path="/dashboard" element={<ProtectedRoute><DashboardRedirect /></ProtectedRoute>} />\n')
    f.write('          <Route path="/manufacturer" element={<ProtectedRoute roles={["manufacturer"]}><ManufacturerDashboard /></ProtectedRoute>} />\n')
    f.write('          <Route path="/manufacturer/*" element={<ProtectedRoute roles={["manufacturer"]}><ManufacturerDashboard /></ProtectedRoute>} />\n')
    f.write('          <Route path="/pharmacist" element={<ProtectedRoute roles={["pharmacist","wholesaler"]}><PharmacistDashboard /></ProtectedRoute>} />\n')
    f.write('          <Route path="/pharmacist/*" element={<ProtectedRoute roles={["pharmacist","wholesaler"]}><PharmacistDashboard /></ProtectedRoute>} />\n')
    f.write('          <Route path="/regulator" element={<ProtectedRoute roles={["regulator"]}><RegulatorDashboard /></ProtectedRoute>} />\n')
    f.write('          <Route path="/regulator/*" element={<ProtectedRoute roles={["regulator"]}><RegulatorDashboard /></ProtectedRoute>} />\n')
    f.write('          <Route path="/patient" element={<ProtectedRoute roles={["patient"]}><PatientPage /></ProtectedRoute>} />\n')
    f.write('          <Route path="/patient/*" element={<ProtectedRoute roles={["patient"]}><PatientPage /></ProtectedRoute>} />\n')
    f.write('        </Routes>\n')
    f.write('      </BrowserRouter>\n')
    f.write('    </AuthProvider>\n')
    f.write('  );\n')
    f.write('}\n')
print('Done')
