with open('src/components/layout/DashboardLayout.jsx', 'w', encoding='utf-8') as f:
    f.write('import Sidebar from "./Sidebar";\n\n')
    f.write('export default function DashboardLayout({ children, title, subtitle }) {\n')
    f.write('  return (\n')
    f.write('    <div className="flex min-h-screen bg-gray-50">\n')
    f.write('      <Sidebar />\n')
    f.write('      <main className="flex-1 overflow-auto">\n')
    f.write('        {title && (\n')
    f.write('          <div className="bg-white border-b border-gray-100 px-8 py-5 sticky top-0 z-10 shadow-sm">\n')
    f.write('            <h1 className="text-2xl font-bold text-gray-900">{title}</h1>\n')
    f.write('            {subtitle && <p className="text-gray-500 text-sm mt-1">{subtitle}</p>}\n')
    f.write('          </div>\n')
    f.write('        )}\n')
    f.write('        <div className="p-8">{children}</div>\n')
    f.write('      </main>\n')
    f.write('    </div>\n')
    f.write('  );\n')
    f.write('}\n')
print('Done')
