with open('src/context/AuthContext.jsx', 'w') as f:
    f.write('import { createContext, useContext, useState, useEffect } from "react";\n')
    f.write('import API from "../utils/api";\n\n')
    f.write('const AuthContext = createContext();\n\n')
    f.write('export const AuthProvider = ({ children }) => {\n')
    f.write('  const [user, setUser] = useState(null);\n')
    f.write('  const [loading, setLoading] = useState(true);\n\n')
    f.write('  useEffect(() => {\n')
    f.write('    const token = localStorage.getItem("access_token");\n')
    f.write('    const savedUser = localStorage.getItem("user");\n')
    f.write('    if (token && savedUser) {\n')
    f.write('      setUser(JSON.parse(savedUser));\n')
    f.write('    }\n')
    f.write('    setLoading(false);\n')
    f.write('  }, []);\n\n')
    f.write('  const login = async (email, password) => {\n')
    f.write('    const res = await API.post("/auth/login/", { email, password });\n')
    f.write('    localStorage.setItem("access_token", res.data.access);\n')
    f.write('    localStorage.setItem("refresh_token", res.data.refresh);\n')
    f.write('    localStorage.setItem("user", JSON.stringify(res.data.user));\n')
    f.write('    setUser(res.data.user);\n')
    f.write('    return res.data.user;\n')
    f.write('  };\n\n')
    f.write('  const logout = () => {\n')
    f.write('    localStorage.clear();\n')
    f.write('    setUser(null);\n')
    f.write('  };\n\n')
    f.write('  const register = async (data) => {\n')
    f.write('    const res = await API.post("/auth/register/", data);\n')
    f.write('    localStorage.setItem("access_token", res.data.access);\n')
    f.write('    localStorage.setItem("refresh_token", res.data.refresh);\n')
    f.write('    localStorage.setItem("user", JSON.stringify(res.data.user));\n')
    f.write('    setUser(res.data.user);\n')
    f.write('    return res.data.user;\n')
    f.write('  };\n\n')
    f.write('  return (\n')
    f.write('    <AuthContext.Provider value={{ user, login, logout, register, loading }}>\n')
    f.write('      {children}\n')
    f.write('    </AuthContext.Provider>\n')
    f.write('  );\n')
    f.write('};\n\n')
    f.write('export const useAuth = () => useContext(AuthContext);\n')
print('Done')
