with open('src/pages/LoginPage.jsx', 'w', encoding='utf-8') as f:
    f.write('import { useState } from "react";\n')
    f.write('import { motion } from "framer-motion";\n')
    f.write('import { useNavigate, Link } from "react-router-dom";\n')
    f.write('import { useAuth } from "../context/AuthContext";\n\n')
    f.write('export default function LoginPage() {\n')
    f.write('  const [email, setEmail] = useState("");\n')
    f.write('  const [password, setPassword] = useState("");\n')
    f.write('  const [error, setError] = useState("");\n')
    f.write('  const [loading, setLoading] = useState(false);\n')
    f.write('  const { login } = useAuth();\n')
    f.write('  const navigate = useNavigate();\n\n')
    f.write('  const handleSubmit = async (e) => {\n')
    f.write('    e.preventDefault();\n')
    f.write('    setLoading(true);\n')
    f.write('    setError("");\n')
    f.write('    try {\n')
    f.write('      const user = await login(email, password);\n')
    f.write('      const routes = { manufacturer: "/manufacturer", pharmacist: "/pharmacist", regulator: "/regulator", patient: "/patient", wholesaler: "/pharmacist" };\n')
    f.write('      navigate(routes[user.role] || "/dashboard");\n')
    f.write('    } catch (err) {\n')
    f.write('      setError(err.response?.data?.detail || "Invalid email or password");\n')
    f.write('    } finally {\n')
    f.write('      setLoading(false);\n')
    f.write('    }\n')
    f.write('  };\n\n')
    f.write('  return (\n')
    f.write('    <div className="min-h-screen bg-gradient-to-br from-primary-900 to-primary-600 flex items-center justify-center px-4">\n')
    f.write('      <motion.div initial={{opacity:0,scale:0.9}} animate={{opacity:1,scale:1}} className="bg-white rounded-2xl shadow-2xl p-8 w-full max-w-md">\n')
    f.write('        <div className="text-center mb-8">\n')
    f.write('          <div className="text-4xl mb-2">💊</div>\n')
    f.write('          <h1 className="text-2xl font-bold text-primary-900">DrugVerify</h1>\n')
    f.write('          <p className="text-gray-500 mt-1">Sign in to your account</p>\n')
    f.write('        </div>\n')
    f.write('        {error && <div className="bg-red-50 text-red-600 px-4 py-3 rounded-lg mb-4 text-sm">{error}</div>}\n')
    f.write('        <form onSubmit={handleSubmit} className="space-y-4">\n')
    f.write('          <div>\n')
    f.write('            <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>\n')
    f.write('            <input type="email" value={email} onChange={e=>setEmail(e.target.value)} required className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-primary-500" placeholder="you@example.com" />\n')
    f.write('          </div>\n')
    f.write('          <div>\n')
    f.write('            <label className="block text-sm font-medium text-gray-700 mb-1">Password</label>\n')
    f.write('            <input type="password" value={password} onChange={e=>setPassword(e.target.value)} required className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-primary-500" placeholder="password" />\n')
    f.write('          </div>\n')
    f.write('          <button type="submit" disabled={loading} className="w-full bg-primary-700 text-white py-3 rounded-lg font-semibold hover:bg-primary-800 transition disabled:opacity-50">\n')
    f.write('            {loading ? "Signing in..." : "Sign In"}\n')
    f.write('          </button>\n')
    f.write('        </form>\n')
    f.write('        <p className="text-center text-gray-500 mt-6 text-sm">Do not have an account? <Link to="/register" className="text-primary-700 font-semibold hover:underline">Register</Link></p>\n')
    f.write('      </motion.div>\n')
    f.write('    </div>\n')
    f.write('  );\n')
    f.write('}\n')
print('Done')
