with open('src/pages/PharmacistDashboard.jsx', 'w', encoding='utf-8') as f:
    f.write('import { useState, useEffect } from "react";\n')
    f.write('import { motion } from "framer-motion";\n')
    f.write('import DashboardLayout from "../components/layout/DashboardLayout";\n')
    f.write('import API from "../utils/api";\n')
    f.write('import { Search, CheckCircle, XCircle, AlertTriangle, Clock, ClipboardList } from "lucide-react";\n\n')
    f.write('export default function PharmacistDashboard() {\n')
    f.write('  const [code, setCode] = useState("");\n')
    f.write('  const [result, setResult] = useState(null);\n')
    f.write('  const [history, setHistory] = useState([]);\n')
    f.write('  const [loading, setLoading] = useState(false);\n')
    f.write('  const [error, setError] = useState("");\n\n')
    f.write('  useEffect(() => { fetchHistory(); }, []);\n\n')
    f.write('  const fetchHistory = async () => {\n')
    f.write('    try { const res = await API.get("/verification/history/"); setHistory(res.data); }\n')
    f.write('    catch(e) { console.error(e); }\n')
    f.write('  };\n\n')
    f.write('  const handleVerify = async (e) => {\n')
    f.write('    e.preventDefault(); setLoading(true); setError(""); setResult(null);\n')
    f.write('    try {\n')
    f.write('      const res = await API.post("/verification/verify/", { scanned_code: code, location: "Lagos, Nigeria" });\n')
    f.write('      setResult(res.data); fetchHistory();\n')
    f.write('    } catch { setError("Verification failed. Please try again."); }\n')
    f.write('    finally { setLoading(false); }\n')
    f.write('  };\n\n')
    f.write('  const resultConfig = {\n')
    f.write('    authentic: { bg: "bg-emerald-50 border-emerald-200", text: "text-emerald-800", icon: CheckCircle, iconColor: "text-emerald-500", label: "Authentic" },\n')
    f.write('    not_found: { bg: "bg-red-50 border-red-200", text: "text-red-800", icon: XCircle, iconColor: "text-red-500", label: "Not Found" },\n')
    f.write('    expired: { bg: "bg-amber-50 border-amber-200", text: "text-amber-800", icon: Clock, iconColor: "text-amber-500", label: "Expired" },\n')
    f.write('    recalled: { bg: "bg-orange-50 border-orange-200", text: "text-orange-800", icon: AlertTriangle, iconColor: "text-orange-500", label: "Recalled" },\n')
    f.write('    counterfeit: { bg: "bg-red-100 border-red-400", text: "text-red-900", icon: XCircle, iconColor: "text-red-600", label: "Counterfeit" },\n')
    f.write('  };\n\n')
    f.write('  const config = result ? (resultConfig[result.result] || resultConfig.not_found) : null;\n\n')
    f.write('  return (\n')
    f.write('    <DashboardLayout title="Drug Verification" subtitle="Enter or scan a batch code to verify drug authenticity">\n')
    f.write('      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">\n\n')
    f.write('        <div className="space-y-6">\n')
    f.write('          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">\n')
    f.write('            <h2 className="text-lg font-bold text-gray-900 mb-1 flex items-center gap-2"><Search className="w-5 h-5 text-primary-700" /> Verify Drug</h2>\n')
    f.write('            <p className="text-sm text-gray-400 mb-6">Enter the batch number from the drug packaging</p>\n')
    f.write('            <form onSubmit={handleVerify} className="space-y-4">\n')
    f.write('              <div>\n')
    f.write('                <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Batch Number</label>\n')
    f.write('                <input value={code} onChange={e=>setCode(e.target.value)} required placeholder="e.g. BATCH-001" className="w-full border-2 border-gray-200 rounded-xl px-4 py-3 text-lg font-mono focus:outline-none focus:border-primary-500 transition tracking-widest" />\n')
    f.write('              </div>\n')
    f.write('              {error && <div className="bg-red-50 border border-red-100 text-red-600 px-4 py-3 rounded-xl text-sm">{error}</div>}\n')
    f.write('              <button type="submit" disabled={loading} className="w-full bg-[#0A2647] text-white py-3.5 rounded-xl font-semibold hover:bg-[#1B4F72] transition disabled:opacity-50 flex items-center justify-center gap-2">\n')
    f.write('                <Search className="w-4 h-4" />\n')
    f.write('                {loading ? "Verifying..." : "Verify Drug"}\n')
    f.write('              </button>\n')
    f.write('            </form>\n')
    f.write('          </div>\n\n')
    f.write('          {result && config && (\n')
    f.write('            <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className={"border-2 rounded-2xl p-6 " + config.bg}>\n')
    f.write('              <div className="flex items-center gap-4 mb-4">\n')
    f.write('                <config.icon className={"w-12 h-12 " + config.iconColor} />\n')
    f.write('                <div>\n')
    f.write('                  <h3 className={"text-2xl font-extrabold " + config.text}>{config.label}</h3>\n')
    f.write('                  <p className={"text-sm " + config.text + " opacity-70"}>Batch: {result.scanned_code}</p>\n')
    f.write('                </div>\n')
    f.write('              </div>\n')
    f.write('              {result.batch && <p className={"text-sm font-medium " + config.text}>{result.batch}</p>}\n')
    f.write('            </motion.div>\n')
    f.write('          )}\n')
    f.write('        </div>\n\n')
    f.write('        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">\n')
    f.write('          <h2 className="text-lg font-bold text-gray-900 mb-1 flex items-center gap-2"><ClipboardList className="w-5 h-5 text-primary-700" /> Verification History</h2>\n')
    f.write('          <p className="text-sm text-gray-400 mb-6">Your recent drug verifications</p>\n')
    f.write('          <div className="space-y-3 max-h-96 overflow-y-auto">\n')
    f.write('            {history.length === 0 ? (\n')
    f.write('              <div className="flex flex-col items-center justify-center py-12 text-gray-300">\n')
    f.write('                <ClipboardList className="w-12 h-12 mb-3" />\n')
    f.write('                <p className="text-gray-400 font-medium">No verifications yet</p>\n')
    f.write('              </div>\n')
    f.write('            ) : history.map(log => (\n')
    f.write('              <div key={log.id} className="flex justify-between items-center p-4 bg-gray-50 rounded-xl border border-gray-100 hover:border-gray-200 transition">\n')
    f.write('                <div>\n')
    f.write('                  <p className="font-semibold text-gray-900 text-sm font-mono">{log.scanned_code}</p>\n')
    f.write('                  <p className="text-xs text-gray-400 mt-0.5">{new Date(log.verified_at).toLocaleString()}</p>\n')
    f.write('                </div>\n')
    f.write('                <span className={"px-3 py-1 rounded-full text-xs font-semibold border " + (log.result === "authentic" ? "bg-emerald-50 text-emerald-700 border-emerald-200" : log.result === "not_found" ? "bg-red-50 text-red-700 border-red-200" : "bg-amber-50 text-amber-700 border-amber-200")}>{log.result.replace("_"," ")}</span>\n')
    f.write('              </div>\n')
    f.write('            ))}\n')
    f.write('          </div>\n')
    f.write('        </div>\n')
    f.write('      </div>\n')
    f.write('    </DashboardLayout>\n')
    f.write('  );\n')
    f.write('}\n')
print('Done')
