with open('src/pages/RegulatorDashboard.jsx', 'w', encoding='utf-8') as f:
    f.write('import { useState, useEffect } from "react";\n')
    f.write('import { motion } from "framer-motion";\n')
    f.write('import DashboardLayout from "../components/layout/DashboardLayout";\n')
    f.write('import API from "../utils/api";\n')
    f.write('import { BarChart2, Pill, Bell, TrendingUp, Users, CheckCircle, AlertTriangle, XCircle } from "lucide-react";\n')
    f.write('import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid } from "recharts";\n\n')
    f.write('const COLORS = ["#10B981","#EF4444","#F59E0B","#3B82F6","#8B5CF6"];\n\n')
    f.write('function StatCard({ title, value, icon: Icon, gradient, delay }) {\n')
    f.write('  return (\n')
    f.write('    <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay}} className={"relative overflow-hidden rounded-2xl p-6 text-white shadow-lg " + gradient}>\n')
    f.write('      <div className="absolute -top-4 -right-4 w-24 h-24 bg-white bg-opacity-10 rounded-full"></div>\n')
    f.write('      <div className="relative">\n')
    f.write('        <div className="w-10 h-10 bg-white bg-opacity-20 rounded-xl flex items-center justify-center mb-4"><Icon className="w-5 h-5 text-white" /></div>\n')
    f.write('        <p className="text-sm font-medium text-white text-opacity-80 mb-1">{title}</p>\n')
    f.write('        <p className="text-4xl font-extrabold">{value}</p>\n')
    f.write('      </div>\n')
    f.write('    </motion.div>\n')
    f.write('  );\n')
    f.write('}\n\n')
    f.write('export default function RegulatorDashboard() {\n')
    f.write('  const [stats, setStats] = useState({});\n')
    f.write('  const [verStats, setVerStats] = useState([]);\n')
    f.write('  const [alerts, setAlerts] = useState([]);\n')
    f.write('  const [drugs, setDrugs] = useState([]);\n')
    f.write('  const [loading, setLoading] = useState(true);\n\n')
    f.write('  useEffect(() => { fetchData(); }, []);\n\n')
    f.write('  const fetchData = async () => {\n')
    f.write('    try {\n')
    f.write('      const [s,v,a,d] = await Promise.all([API.get("/analytics/dashboard/"),API.get("/analytics/verifications/"),API.get("/alerts/"),API.get("/drugs/")]);\n')
    f.write('      setStats(s.data); setVerStats(v.data); setAlerts(a.data); setDrugs(d.data);\n')
    f.write('    } catch(e) { console.error(e); }\n')
    f.write('    finally { setLoading(false); }\n')
    f.write('  };\n\n')
    f.write('  const resolveAlert = async (id) => {\n')
    f.write('    try { await API.post("/alerts/" + id + "/resolve/"); fetchData(); }\n')
    f.write('    catch(e) { console.error(e); }\n')
    f.write('  };\n\n')
    f.write('  if (loading) return <DashboardLayout title="Regulator Dashboard"><div className="flex items-center justify-center h-64"><div className="animate-spin rounded-full h-10 w-10 border-4 border-gray-200 border-t-purple-700"></div></div></DashboardLayout>;\n\n')
    f.write('  return (\n')
    f.write('    <DashboardLayout title="Regulator Dashboard" subtitle="Monitor all drugs, alerts and verifications across the system">\n\n')
    f.write('      <div className="grid grid-cols-2 lg:grid-cols-4 gap-5 mb-8">\n')
    f.write('        <StatCard title="Total Drugs" value={stats.total_drugs ?? 0} icon={Pill} gradient="bg-gradient-to-br from-[#0A2647] to-[#2E86C1]" delay={0} />\n')
    f.write('        <StatCard title="Verifications" value={stats.total_verifications ?? 0} icon={TrendingUp} gradient="bg-gradient-to-br from-emerald-600 to-emerald-400" delay={0.1} />\n')
    f.write('        <StatCard title="Unresolved Alerts" value={stats.unresolved_alerts ?? 0} icon={AlertTriangle} gradient="bg-gradient-to-br from-rose-600 to-rose-400" delay={0.2} />\n')
    f.write('        <StatCard title="Supply Events" value={stats.total_supply_chain_events ?? 0} icon={BarChart2} gradient="bg-gradient-to-br from-violet-600 to-violet-400" delay={0.3} />\n')
    f.write('      </div>\n\n')
    f.write('      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">\n')
    f.write('        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">\n')
    f.write('          <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2"><BarChart2 className="w-5 h-5 text-primary-700" /> Verification Results</h2>\n')
    f.write('          {verStats.length > 0 ? (\n')
    f.write('            <ResponsiveContainer width="100%" height={250}>\n')
    f.write('              <PieChart><Pie data={verStats} dataKey="count" nameKey="result" cx="50%" cy="50%" outerRadius={90} label={({result,percent}) => result + " " + (percent*100).toFixed(0) + "%"}>{verStats.map((_,i) => <Cell key={i} fill={COLORS[i%COLORS.length]} />)}</Pie><Tooltip /></PieChart>\n')
    f.write('            </ResponsiveContainer>\n')
    f.write('          ) : <div className="flex items-center justify-center h-48 text-gray-300"><p>No verification data yet</p></div>}\n')
    f.write('        </div>\n\n')
    f.write('        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">\n')
    f.write('          <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2"><Bell className="w-5 h-5 text-red-500" /> Active Alerts</h2>\n')
    f.write('          <div className="space-y-3 max-h-56 overflow-y-auto">\n')
    f.write('            {alerts.filter(a => !a.is_resolved).length === 0 ? (\n')
    f.write('              <div className="flex flex-col items-center justify-center py-10 text-gray-300"><CheckCircle className="w-10 h-10 mb-2" /><p className="text-gray-400">No active alerts</p></div>\n')
    f.write('            ) : alerts.filter(a => !a.is_resolved).map(alert => (\n')
    f.write('              <div key={alert.id} className="flex justify-between items-center p-4 bg-red-50 rounded-xl border border-red-100">\n')
    f.write('                <div>\n')
    f.write('                  <p className="font-semibold text-gray-900 text-sm">{alert.title}</p>\n')
    f.write('                  <div className="flex items-center gap-2 mt-1">\n')
    f.write('                    <span className={"px-2 py-0.5 rounded-full text-xs font-semibold " + (alert.severity === "high" || alert.severity === "critical" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-700")}>{alert.severity}</span>\n')
    f.write('                    <span className="text-xs text-gray-400 capitalize">{alert.alert_type}</span>\n')
    f.write('                  </div>\n')
    f.write('                </div>\n')
    f.write('                <button onClick={() => resolveAlert(alert.id)} className="text-xs bg-emerald-100 text-emerald-700 border border-emerald-200 px-3 py-1.5 rounded-lg hover:bg-emerald-200 transition font-medium">Resolve</button>\n')
    f.write('              </div>\n')
    f.write('            ))}\n')
    f.write('          </div>\n')
    f.write('        </div>\n')
    f.write('      </div>\n\n')
    f.write('      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">\n')
    f.write('        <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2"><Pill className="w-5 h-5 text-primary-700" /> All Drugs</h2>\n')
    f.write('        <div className="overflow-x-auto">\n')
    f.write('          <table className="w-full text-sm">\n')
    f.write('            <thead><tr className="bg-gray-50 border-b border-gray-100">{["Drug Name","NAFDAC No.","Manufacturer","Dosage Form","Status"].map(h => <th key={h} className="text-left py-3 px-5 text-xs font-semibold text-gray-400 uppercase tracking-wider">{h}</th>)}</tr></thead>\n')
    f.write('            <tbody className="divide-y divide-gray-50">\n')
    f.write('              {drugs.length === 0 ? (\n')
    f.write('                <tr><td colSpan={5} className="py-12 text-center text-gray-400">No drugs found</td></tr>\n')
    f.write('              ) : drugs.map(drug => (\n')
    f.write('                <tr key={drug.id} className="hover:bg-gray-50 transition">\n')
    f.write('                  <td className="py-4 px-5 font-semibold text-gray-900">{drug.name}</td>\n')
    f.write('                  <td className="py-4 px-5 font-mono text-xs text-gray-500">{drug.nafdac_number}</td>\n')
    f.write('                  <td className="py-4 px-5 text-gray-500">{drug.manufacturer_name}</td>\n')
    f.write('                  <td className="py-4 px-5 text-gray-500">{drug.dosage_form}</td>\n')
    f.write('                  <td className="py-4 px-5"><span className={"px-3 py-1 rounded-full text-xs font-semibold border " + (drug.status === "active" ? "bg-emerald-50 text-emerald-700 border-emerald-200" : "bg-red-50 text-red-700 border-red-200")}>{drug.status}</span></td>\n')
    f.write('                </tr>\n')
    f.write('              ))}\n')
    f.write('            </tbody>\n')
    f.write('          </table>\n')
    f.write('        </div>\n')
    f.write('      </div>\n')
    f.write('    </DashboardLayout>\n')
    f.write('  );\n')
    f.write('}\n')
print('Done')
