with open('tailwind.config.js', 'w', encoding='utf-8') as f:
    f.write('/** @type {import("tailwindcss").Config} */\n')
    f.write('export default {\n')
    f.write('  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],\n')
    f.write('  theme: {\n')
    f.write('    extend: {\n')
    f.write('      colors: {\n')
    f.write('        primary: {\n')
    f.write('          900: "#0A2647",\n')
    f.write('          700: "#1B4F72",\n')
    f.write('          500: "#2E86C1",\n')
    f.write('          100: "#EBF5FB",\n')
    f.write('        },\n')
    f.write('        success: "#10B981",\n')
    f.write('        danger: "#EF4444",\n')
    f.write('        warning: "#F59E0B",\n')
    f.write('      },\n')
    f.write('      fontFamily: {\n')
    f.write('        sans: ["Inter", "sans-serif"],\n')
    f.write('      },\n')
    f.write('      boxShadow: {\n')
    f.write('        card: "0 1px 3px rgba(0,0,0,0.05), 0 1px 2px rgba(0,0,0,0.1)",\n')
    f.write('        "card-hover": "0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05)",\n')
    f.write('      },\n')
    f.write('    },\n')
    f.write('  },\n')
    f.write('  plugins: [],\n')
    f.write('}\n')
print('Done')
